- hosts: target-server
  become: true
  tasks:
    - name: Créer un fichier de trace depuis Jenkins/Ansible
      copy:
        content: "Playbook exécuté via Jenkins à {{ ansible_date_time.iso8601 }}\n"
        dest: /tmp/jenkins_ansible_trace.txt
